spring.application.name=arena-pernambuco
server.port=8080
spring.thymeleaf.cache=false

spring.profiles.active=firebase
firebase.credentials.path=/projeto-arena-pernambuco-firebase-adminsdk-fbsvc-6910d1e348.json
firebase.database.url=https://projeto-arena-pernambuco-default-rtdb.firebaseio.com
